### ISSUE TITLE
Use argparse instead of manually parsing sys.argv?

### ISSUE THREAD

**Issue by wylee** [PSU-OIT-ARC/httpd-multi#2]
This is just a suggestion/proposal. I'm not a fan of manually parsing `sys.argv`. Using `argparse` has very little overhead and would probably make the script a little simpler and easier to extend. I'll make the change if no one objects.

@mdj2 
@yorkedork

**Comment by mdj2** [comment]
Feel free. Using argparse would be beneficial if we start adding more arguments. httpd-multi is a dumb wrapper around httpd, but I suppose it might need to become more complex overtime.

**Comment by thomlinton** [comment]
Yes. +1

It's probably worth noting that argparse must be installed from pip if using Python < 2.7.

I was tempted to take this approach myself before I considered that I should remain focused on my actual needs.

I think a reasonable goal would be to collapse much of the `__name__ == '__main__'`: ultimately, I'm thinking the actual CLI bits should be separated from the vhost proxy and application config generation.
